#!/bin/sh
bemenu-run \
  -b \
  -H 30 \
  --fn "JetBrainsMono Nerd Font 9" \
  --tb "#fe8019" \
  --tf "#000000" \
  --fb "#1d2021" \
  --ff "#8ec07c" \
  --cb "#000000" \
  --cf "#fbf1c7" \
  --nb "#282828" \
  --nf "#fbf1c7" \
  --hb "#fbf1c7" \
  --hf "#000000" \
  --ab "#3c3836" \
  --af "#d5c4a1"
