#!/bin/sh

dispositovo_opcoes=$(wpctl status | grep -m1 -A 5 "Sinks:" | head -n 10 | tr -d '│'" " | cut -d"*" -f2 | sed -n '/^[[:digit:]]/p' | bemenu -Tn -H 20 --fn "JetBrainsMono Nerd Font 9" -p "pipewire wpctl")

echo $dispositovo_opcoes

dispositivo_numero=$(echo $dispositovo_opcoes | cut -d. -f1)

# echo $dispositivo_numero

wpctl set-default $dispositivo_numero &> /dev/null

