#!/bin/env bash

dispositovo_opcoes=$(wpctl status | grep -m1 -A 5 "Sinks:" | head -n 10 | tr -d '│'" " | cut -d"*" -f2 | sed -n '/^[[:digit:]]/p' | cut -d\[ -f1 | wofi -dmenu -s ~/.config/wofi/style_wpctl.css -c ~/.config/wofi/config.wpctl)

echo $dispositovo_opcoes

dispositivo_numero=$(echo $dispositovo_opcoes | cut -d. -f1)

# echo $dispositivo_numero

wpctl set-default $dispositivo_numero &> /dev/null

