# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()
# usar antialiase para usar fonte monaco
c.fonts.tabs = "11pt misc ohsnap"
c.fonts.statusbar = "10pt misc ohsnap"
# c.fonts.hints = "11pt monospace bold"
c.fonts.messages.info = "10pt misc ohsnap"
c.fonts.downloads = c.fonts.statusbar
c.fonts.prompts = "8pt monaco"
c.fonts.keyhint = c.fonts.messages.info
c.fonts.messages.warning = c.fonts.messages.info
c.fonts.messages.error = c.fonts.messages.info
c.fonts.completion.entry = "8pt monaco for powerline"
c.fonts.completion.category = c.fonts.statusbar
