#! /bin/sh

chosen=$(printf "  Desligar\n  Reiniciar\n󱂅 󰗽 Log Out" | fuzzel --lines=3 --width=13  -d --placeholder=" Sair")

case "$chosen" in
	"  Desligar") poweroff ;;
	"  Reiniciar") reboot ;;
	"󱂅 󰗽 Log Out") hyrpctl exit ;;
	*) exit 1 ;;
esac

	# "  Suspend") systemctl suspend-then-hibernate ;;
	# "  Hibernate") systemctl hibernate ;;
	# "  Lock") betterlockscreen -l ;;
# vim-ft:sh
