#!/bin/sh

pid=$(pgrep -c gammastep)

if [ $pid -gt 0 ]; then
  if pgrep -x "gammastep" >/dev/null; then
    notify-send "Nightlight is off"
    kill -9 $(pgrep -x "gammastep")
  else
    notify-send "Nightlight is on"
    gammastep #-O ${GAMMASTEP_NIGHT:-3500} &
  fi
fi
