# search
c.url.searchengines['DEFAULT'] = 'https://www.duckduckgo.com/?q={}'
c.url.searchengines['g'] = 'https://www.google.com/search?q={}'
c.url.searchengines['m'] = 'https://www.google.com/maps?q={}'
c.url.searchengines['k'] = 'https://keep.google.com/#search/text%253D{}'
c.url.searchengines['w'] = 'http://pt.wikipedia.org/w/index.php?search={}&title=Special:Search'
c.url.searchengines['y'] = 'https://www.youtube.com/results?search_query={}'
c.url.searchengines['ar'] = 'https://wiki.archlinux.org/?search={}'
c.url.searchengines['v'] = 'https://wiki.voidlinux.org/?search={}'
c.url.searchengines['ge'] = 'https://wiki.gentoo.org/wiki/?search={}'
c.url.searchengines['t'] = 'https://translate.google.com/#view=home&op=translate&sl=en&tl=pt&text={}'
c.url.searchengines['rd'] = 'https://reddit.com/search/?q={}'
c.url.searchengines['l'] = 'https://www.deepl.com/pt-BR/translator#en/pt-br/{}'
c.url.searchengines['b'] = 'https://bastos.bibipecas.com.br/search/{}'
c.url.searchengines['n'] = 'https://www.netflix.com/search?q={}'
c.url.searchengines['i'] = 'https://yewtu.be/search?q={}'
c.url.searchengines['p'] = 'https://piped.kavin.rocks/results?search_query={}'
c.url.searchengines['dc'] = 'http://downloadcult.org/?s={}'
