format = """
[ ](#d65d0e)\
[  ](bg:#d65d0e fg:#090c0c)\
[](bg:#fe8019 fg:#d65d0e)\
$directory\
[](fg:#fe8019 bg:#076678)\
$git_branch\
$git_status\
[](fg:#076678 bg:#282828)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#282828 bg:#1d2230)\
$time\
[ ](fg:#1d2230)\
\n$character"""

[directory]
style = "fg:#1d2021 bg:#fe8019"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#076678"
format = '[[ $symbol $branch ](fg:#fbf1c7 bg:#076678)]($style)'

[git_status]
style = "bg:#076678"
format = '[[($all_status$ahead_behind )](fg:#fbf1c7 bg:#076678)]($style)'

[nodejs]
symbol = ""
style = "bg:#282828"
format = '[[ $symbol ($version) ](fg:#fbf1c7 bg:#282828)]($style)'

[rust]
symbol = ""
style = "bg:#282828"
format = '[[ $symbol ($version) ](fg:#fbf1c7 bg:#282828)]($style)'

[golang]
symbol = ""
style = "bg:#282828"
format = '[[ $symbol ($version) ](fg:#fbf1c7 bg:#282828)]($style)'

[php]
symbol = ""
style = "bg:#282828"
format = '[[ $symbol ($version) ](fg:#fbf1c7 bg:#282828)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
