#!/bin/bash

#     ▄▄▄▄     ██████  ██▓███   █     █░ ███▄ ▄███▓
#    ▓█████▄ ▒██    ▒ ▓██░  ██▒▓█░ █ ░█░▓██▒▀█▀ ██▒
#    ▒██▒ ▄██░ ▓██▄   ▓██░ ██▓▒▒█░ █ ░█ ▓██    ▓██░
#    ▒██░█▀    ▒   ██▒▒██▄█▓▒ ▒░█░ █ ░█ ▒██    ▒██
#    ░▓█  ▀█▓▒██████▒▒▒██▒ ░  ░░░██▒██▓ ▒██▒   ░██▒
#    ░▒▓███▀▒▒ ▒▓▒ ▒ ░▒▓▒░ ░  ░░ ▓░▒ ▒  ░ ▒░   ░  ░
#    ▒░▒   ░ ░ ░▒  ░ ░░▒ ░       ▒ ░ ░  ░  ░      ░
#     ░    ░ ░  ░  ░  ░░         ░   ░  ░      ░
#     ░            ░               ░           ░

. "${HOME}/.cache/wal/colors.sh"

bspc monitor -d TER-1 WEB-2 MPV-3 CODE-4 WORK-5 FILE-6 EDIT-7 GAME-8 MAIL-9 MPD-10

bspc config border_width         2

gap=0
PANEL_HEIGHT=0

position_new_window=longest_side
# position_new_window=alternate
# position_new_window=spiral

# pode deixar PANEL_HEIGHT=0 se comentar [global/wm] em polybar.conf ;margin-top = 5 ;margin-bottom = 5
export gap
export PANEL_HEIGHT

bspc config window_gap                      $gap
bspc config top_padding                     $PANEL_HEIGHT

bspc config split_ratio                     0.0
bspc config borderless_monocle              true
bspc config gapless_monocle                 true
#bspc config focus_by_distance               true
bspc config focus_follows_pointer           false
#bspc config auto_cancel                     true
bspc config initial_polarity                second_child
bspc config automatic_scheme                $position_new_window
bspc config single_monocle 	                true


bspc config normal_border_color             "#222"
# bspc config normal_border_color           "$color0"
bspc config focused_border_color            "#fe8019"
# bspc config focused_border_color          "$color12"
bspc config presel_feedback_color           "#2aa198"
bspc config active_border_color             "#ffffff"

bspc rule -a Gimp state=floating follow=on
bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a Steam desktop='^8' follow=on border=off
bspc rule -a Mplayer state=floating
# bspc rule -a Mousepad state=floating
bspc rule -a qutebrowser desktop='^2' follow=on
bspc rule -a Chromium desktop='^3' follow=on border=on
bspc rule -a mpv state=floating
bspc rule -a feh state=floating
bspc rule -a TelegramDesktop state=floating rectangle=400x625+1512+18
bspc rule -a Pavucontrol state=floating rectangle=800x625+1110+18
bspc rule -a "Code - OSS" desktop='^4' follow=on
# bspc desktop 'WEB-2' --layout monocle

# polybar example &
$HOME/.config/polybar/launch.sh
# picom &
# redshift; redshift -t 5100:3900 -l -1.396142:-48.386560
# feh --bg-scale "$(< "${HOME}/.cache/wal/wal")"
