#!/bin/bash

#     ▄▄▄▄     ██████  ██▓███   █     █░ ███▄ ▄███▓
#    ▓█████▄ ▒██    ▒ ▓██░  ██▒▓█░ █ ░█░▓██▒▀█▀ ██▒
#    ▒██▒ ▄██░ ▓██▄   ▓██░ ██▓▒▒█░ █ ░█ ▓██    ▓██░
#    ▒██░█▀    ▒   ██▒▒██▄█▓▒ ▒░█░ █ ░█ ▒██    ▒██
#    ░▓█  ▀█▓▒██████▒▒▒██▒ ░  ░░░██▒██▓ ▒██▒   ░██▒
#    ░▒▓███▀▒▒ ▒▓▒ ▒ ░▒▓▒░ ░  ░░ ▓░▒ ▒  ░ ▒░   ░  ░
#    ▒░▒   ░ ░ ░▒  ░ ░░▒ ░       ▒ ░ ░  ░  ░      ░
#     ░    ░ ░  ░  ░  ░░         ░   ░  ░      ░
#     ░            ░               ░           ░
  
 
#bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc monitor -d TER-1 WEB-2 MPV-3 CODE-4 WORK-5 FILE-6 EDIT-7 GAME-8 MAIL-9 MPD-10

bspc config border_width         2

gap=5
PANEL_HEIGHT=0

# pode deixar PANEL_HEIGHT=0 se comentar [global/wm] em polybar.conf ;margin-top = 5 ;margin-bottom = 5
export gap
export PANEL_HEIGHT

bspc config window_gap                    $gap
bspc config top_padding                   $PANEL_HEIGHT

bspc config split_ratio                   0.5
bspc config borderless_monocle            true
bspc config gapless_monocle               true
#bspc config focus_by_distance             true
bspc config focus_follows_pointer         false
#bspc config auto_cancel                   true
bspc config initial_polarity              second_child
bspc config automatic_scheme              alternate


bspc config normal_border_color           "#222"
bspc config focused_border_color          "#00afaf"
bspc config presel_feedback_color         "#bbaa00"
bspc config active_border_color           "#ffffff"

bspc rule -a Gimp state=floating follow=on
bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a Steam desktop='^8' follow=on
bspc rule -a Mplayer state=floating
#bspc rule -a Mousepad state=floating
bspc rule -a qutebrowser desktop='^2' follow=on border=off
bspc rule -a mpv state=floating
bspc rule -a feh state=floating
bspc desktop 'WEB-2' --layout monocle

#polybar example &
$HOME/.config/polybar/launch.sh
#picom &
#redshift; redshift -t 5100:3900 -l -1.396142:-48.386560
#feh --bg-scale "$(< "${HOME}/.cache/wal/wal")"
