import = [
"~/.config/alacritty/themes/themes/tokyo-night.toml",
"~/.config/alacritty/keybindings.toml",
]

[cursor]
vi_mode_style = "Block"
style = { shape = "Beam", blinking = "On" }

[colors]
vi_mode_cursor = { text = "CellForeground", cursor = "#00ff00" } 

[font]
size = 9.5
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"

[window]
opacity = 0.9
padding.x = 0
padding.y = 0
decorations = "Full"
# decorations_theme_variant = "Light" # "Dark"
